create intermidiate models(with discount for customer and margin for provider and car_showroom)
CeNTePeDe/show_room pull request #3
Opened 2023-04-10 12:58 UTC by CeNTePeDe

2023-04-11 16:30 UTC, slavadan requested changes

2023-04-11 16:30 UTC, slavadan commented on show_room/cars/models.py
> +    name = models.CharField(max_length=40, verbose_name="name car")
car name

2023-04-11 16:30 UTC, slavadan commented on show_room/customer/models.py
> +class CustomerCarShowroom(models.Model):
Если я правильно понял, то эта таблица будет использоваться для отчетности покупок машин покупателя у автосалона. Тогда как ты будешь понимать какую машину купили и за сколько? Так же можно не использовать M2M связь тк у одного покупателя есть много покупок т.е тут связь One to Many от покупателя к этой таблице соотв. можно переименовать таблица наподобие "Покупки" или "Транзакция" или как-то еще чтобы она отображала смысл. Также рекомендую оставлять doc strings, чтобы описать класс и его смысл(было бы очень круто, мне так будет проще понять для чего эта будет использоваться").

2023-04-11 16:30 UTC, slavadan commented on show_room/show_room/settings.py
> +        "PORT": "5432",
порты тоже в енв файл закинь

2023-04-11 16:31 UTC, slavadan commented
А где акции?

2023-04-11 16:31 UTC, slavadan commented
и почему 3pr O_O

2023-04-11 16:43 UTC, slavadan commented
Соблюдай нейминг коммитов пожалуйста(я уже описывал как их называть, делаешь правки fix: .... что-то, делаешь что-то новое feature: create models for Provider, ShowRoom, Customer), локально ты можешь хоть ffff в названии писать, но когда делаешь pr он должен быть красивым. У тебя 2 маленьких коммита с одинаковым названием. Используй squash коммитов, чтобы их объеденить.

2023-04-12 06:20 UTC, CeNTePeDe commented on show_room/customer/models.py
> +    discount = models.IntegerField(default=0, choices=CHOICE_DISCOUNT)
создать отдельную таблицу для моделей и через ForeignKey связать 
идея только такая

2023-04-12 07:27 UTC, CeNTePeDe commented on show_room/show_room/settings.py
> +        "PORT": "5432",
вчера мы вообще все вернули, тк не сработало

2023-04-12 07:45 UTC, slavadan commented on show_room/customer/models.py
> +    discount = models.IntegerField(default=0, choices=CHOICE_DISCOUNT)
да

2023-04-12 08:35 UTC, CeNTePeDe commented on show_room/customer/models.py
> +class CustomerCarShowroom(models.Model):
как я поняла (из дока), переделываю связь на foreign key, там тож промежуточная таблица, ее под транзакции, и может там пробросить машины, чтобы покупатель мог подыскать себе лучший вариант, и от этого уже какой салон

2023-04-13 17:08 UTC, closed without merging